version: "3"

services:
  api1:
    build: ./One
    container_name: api1
    ports:
      - "3000:3000"

  api2:
    build: ./Two
    container_name: api2
    ports:
      - "4000:4000"

  nginx_lb:
    image: nginx
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api1
      - api2
    networks:
      - hira
networks:
  hira:
    driver: bridge
