version: "3"

services:
  api1:
    build:
      context: ./One
      dockerfile: Dockerfile.app1 # Specify the new Dockerfile name here
    container_name: api1
    ports:
      - "3000:3000"
    networks:
      - hira

  api2:
    build:
      context: ./Two
      dockerfile: Dockerfile.app2 # Specify the new Dockerfile name here
    container_name: api2
    ports:
      - "4000:4000"
    networks:
      - hira

  nginx_lb:
    image: nginx
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api1
      - api2
    networks:
      - hira

networks:
  hira:
    driver: bridge
